### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by fire** [fwsGonzo/rvscript#2]
Can you use the same license https://github.com/fwsGonzo/libriscv/blob/master/LICENSE? Unless you want to remove the binary advertising clause? I would assume distributing the license text for 128 instructions would be cumbersome.

**Comment by fwsGonzo** [comment]
This repository is intended to be public domain. I'll try to find an appropriate license for that.

**Comment by fire** [comment]
I would suggest https://creativecommons.org/share-your-work/public-domain/cc0/ for all of the changes you made and then for each dependent project state their license.

**Comment by fwsGonzo** [comment]
While I liked the idea of cc0, I could not fully understand it, so I chose the MIT license instead. Hope that works for you!

**Comment by fire** [comment]
Thanks
